Add optional support for using RUNNER_TOKEN instead of GITHUB_PAT
redhat-actions/openshift-actions-runners pull request #10
Opened 2021-06-01 17:54 UTC by willhaines

### Description

Allows users to manually generate a narrowly-scoped runner registration token, rather than a long-lived PAT, with the expense of additional complexity. Existing PAT functionality is unchanged -- except that omission of GITHUB_PAT env variable is no longer fatal.

### Related Issue(s)

Resolves #9 

### Checklist

- [x] This PR includes a documentation change
- [ ] This PR does not need a documentation change
---
- [ ] This PR includes test changes
- [ ] This PR's changes are already tested
- [x] This PR's changes were tested manually
---
- [ ] This change is a patch change
- [x] This change is a minor change
- [ ] This change is a major (breaking) change

### Changes made

- Made $GITHUB_PAT env variable optional
- Split registration steps into separate script for optional use of an init Job in Kubernetes
- Documented persistence with a volume when not using a PAT

2021-06-03 14:20 UTC, tetchel requested changes
Thank you for this high-quality PR! I just have one concern about the default behaviour if required environment variables are missing.

2021-06-03 14:20 UTC, tetchel commented on base/register.sh
> +    echo "Visit ${registration_url}/settings/actions/runners to manually force removal of runner."
isn't `registration_url` unset at the time this is echoed?

2021-06-03 14:20 UTC, tetchel commented on base/register.sh
> +registration_url="https://${GITHUB_DOMAIN}/${GITHUB_OWNER}${GITHUB_REPOSITORY:+/$GITHUB_REPOSITORY}"
TIL about `:+` for variable expansion :+1:

2021-06-03 14:20 UTC, tetchel commented on base/entrypoint.sh
> +    echo "No GITHUB_PAT or RUNNER_TOKEN provided. Assuming creds file provided in /home/runner."
My only concern with this behaviour is that it makes this the default case if a user misconfigures their container and fails to set one of these env vars, even if they have not already run the config script. Then the runner will fail to start up.

Instead of "assuming creds file provided", can we check for a file that would exist if the config has already run? do you know what file may indicate that?

2021-06-03 14:20 UTC, tetchel commented on base/entrypoint.sh
> +    echo "No GITHUB_PAT or RUNNER_TOKEN provided. Assuming creds file provided in /home/runner."
Also, instead of `/home/runner`, I think this should be `${RUNNER_WORKDIR}`.

2021-06-07 22:37 UTC, willhaines commented on base/register.sh
> +    echo "Visit ${registration_url}/settings/actions/runners to manually force removal of runner."
Good catch. I'll move that block a bit further down.

2021-06-07 23:34 UTC, willhaines commented on base/entrypoint.sh
> +    echo "No GITHUB_PAT or RUNNER_TOKEN provided. Assuming creds file provided in /home/runner."
Good suggestion! I like the idea of checking for the credentials file directly. I believe the file to look for would be `.credentials`.

Regarding `${RUNNER_WORKDIR}` vs `/home/runner`: Unfortunately, the `./config.sh` script creates several files adjacent to itself, including `.credentials`, that appear to be necessary for subsequent runner starts.

```
$ diff -bur before-register after-register
Only in after-register/home/runner: .credentials
Only in after-register/home/runner: .credentials_rsaparams
Only in after-register/home/runner: _diag
Only in after-register/home/runner: .env
Only in after-register/home/runner: .path
Only in after-register/home/runner: .runner
Only in after-register/home/runner: svc.sh
```

I may be missing something, but there doesn't appear to be any flag to override this behavior and specify an alternate destination for these files. We could narrow the scope of what needs to be persisted by installing the actions runner in a subdirectory, or attempting to maintain a script that copies only the minimum set of necessary files.

What do you think?

2021-06-08 13:00 UTC, tetchel commented on base/entrypoint.sh
> +    echo "No GITHUB_PAT or RUNNER_TOKEN provided. Assuming creds file provided in /home/runner."
you're right, runner workdir is not the right value.

it could be `$HOME`, or it could even be `$PWD`. Probably $PWD is best since we rely on `config.sh` and the other runner scripts to be in `.`

2021-06-09 22:23 UTC, willhaines commented on README.md
> +    quay.io/redhat-github-actions/runner:v1.0.0 \
Thanks @tetchel for all of the good feedback. I think I'm done now, unless you have any more concerns. One last question that I had, is how you handle version bumps?

I would assume this change would take us to 1.1.0 since it introduces a new feature, but doesn't break existing functionality, but you may have some other versioning scheme in mind.

2021-06-10 00:02 UTC, tetchel commented on README.md
> +    quay.io/redhat-github-actions/runner:v1.0.0 \
Yes I think this constitutes a semver minor release, as you selected in the PR template above. I'll tag 1.1.0 once this is merged

2021-06-10 13:31 UTC, tetchel approved these changes

2021-06-10 15:18 UTC, tetchel commented
hey, sorry to only notice this now, but can you sign your commits?

you can do so either with a rebase and `reword` each commit, or you can just squash the commits into a new one:
```
git reset upstream/main
git commit -s -m "Add optional support for using RUNNER_TOKEN instead of GITHUB_PAT"
git push origin main -f
```

2021-06-11 15:54 UTC, merged

2021-06-11 16:27 UTC, tetchel commented
after a small readme update, i've released v1.1.0 and rolled forward v1.

thank you for this contribution!